FROM rust:1.67 as develop-stage
WORKDIR /app
COPY ./rust-app/ ./
RUN cargo install cargo-watch sccache

FROM develop-stage as build-stage
RUN cargo build --release

FROM rust:1.67-slim-stretch
WORKDIR /app
COPY --from=build-stage /app/target/release/api .
CMD ["/app/api"]
