FROM python:3.8-buster as builder
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY ./docker/bff/requirements.txt .
RUN /usr/local/bin/python -m pip install --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt